name: playground
synopsis: Coding playground for Haskell-based experiments
description: Coding playground for Haskell-based experiments
version: 0.0.1
homepage: https://github.com/luc-tielen/playground#README.md
license: MIT
author: Luc Tielen
maintainer: luc.tielen@gmail.com
copyright: 2021 Luc Tielen
category: Compilers, Logic Programming
github: luc-tielen/playground
extra-source-files:
  - README.md
  - LICENSE

dependencies:
  - base >= 4.12 && < 5
  - mtl >= 2.0 && < 3
  - text >= 1.0 && < 2
  - containers >= 0.6.2.1 && < 1
  - recursion-schemes
  - souffle-haskell

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - ScopedTypeVariables

ghc-options:
  - -Wall
  - -Weverything
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-implicit-prelude
  - -Wno-missed-specializations
  - -Wno-all-missed-specializations
  - -Wno-missing-import-lists
  - -Wno-type-defaults
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-missing-deriving-strategies
  - -Wno-prepositive-qualified-module
  - -Wno-missing-safe-haskell-mode
  - -optP-Wno-nonportable-include-path
  - -fhide-source-paths
  - -fno-show-valid-hole-fits
  - -fno-sort-valid-hole-fits

executables:
  playground:
    source-dirs:      src
    main:             Main.hs
    cxx-sources: cbits/*.cpp
    cxx-options:
      - -std=c++17
      - -Wall
      - -D__EMBEDDED_SOUFFLE__
    when:
      - condition: os(linux)
        extra-libraries: stdc++
